<?php

namespace Database\Seeders;

use App\Models\Team;
use App\Utility\Enums\TeamStatus;
use Illuminate\Database\Seeder;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teams = [
            [
                'name' => 'الأهلي (Al Ahly SC)',
                'short_name' => 'AHL',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@alahlyegypt.com',
                'phone' => '+20227355555',
                'manager_name' => 'ستيفان مادسن (Stefan Madsen)',
                'arena' => 'صالة الأمير عبد الله الفيصل بالجزيرة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الزمالك (Zamalek SC)',
                'short_name' => 'ZAM',
                'city' => 'الجيزة',
                'country' => 'مصر',
                'email' => 'handball@zamalek.org',
                'phone' => '+20233470000',
                'manager_name' => 'فرناندو باربيتو (Fernando Barbeito)',
                'arena' => 'صالة عبد الرحمن فوزي بميت عقبة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'سبورتنج (Sporting Club)',
                'short_name' => 'SPO',
                'city' => 'الإسكندرية',
                'country' => 'مصر',
                'email' => 'handball@sportingclub.eg',
                'phone' => '+2035432100',
                'manager_name' => 'أشرف عواض',
                'arena' => 'صالة نادي سبورتنج بالإسكندرية',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'سموحة (Smouha SC)',
                'short_name' => 'SMO',
                'city' => 'الإسكندرية',
                'country' => 'مصر',
                'email' => 'handball@smouhaclub.com',
                'phone' => '+2034255555',
                'manager_name' => 'محمد عبد السلام',
                'arena' => 'صالة نادي سموحة الكبرى',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'طلائع الجيش (Tala\'ea El Gaish)',
                'short_name' => 'TGS',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@elgaish.org',
                'phone' => '+20222610000',
                'manager_name' => 'طارق محروس',
                'arena' => 'صالة جهاز الرياضة العسكري بكوبري القبة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'البنك الأهلي (National Bank of Egypt)',
                'short_name' => 'NBE',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@nbeclub.com',
                'phone' => '+20223900000',
                'manager_name' => 'عمرو الجيوشي',
                'arena' => 'صالة اتحاد الشرطة بالدراسة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'هليوبوليس (Heliopolis SC)',
                'short_name' => 'HEL',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@heliopolisclub.com',
                'phone' => '+20224150000',
                'manager_name' => 'أحمد دعبس',
                'arena' => 'صالة نادي هليوبوليس بالشروق',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الأولمبي (Olympic Club)',
                'short_name' => 'OLY',
                'city' => 'الإسكندرية',
                'country' => 'مصر',
                'email' => 'handball@olympic-club.eg',
                'phone' => '+2034950000',
                'manager_name' => 'حسام غريب',
                'arena' => 'صالة النادي الأولمبي بوابل المياه',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الطيران (Aviation Club)',
                'short_name' => 'TAY',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@aviationclub.org',
                'phone' => '+20222670000',
                'manager_name' => 'محمد يحيى',
                'arena' => 'صالة نادي الطيران بمدينة نصر',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الجزيرة (Gezira SC)',
                'short_name' => 'GEZ',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@geziraclub.com',
                'phone' => '+20227360000',
                'manager_name' => 'خالد فتحي',
                'arena' => 'صالة نادي الجزيرة بالزمالك',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الزهور (El Zohour SC)',
                'short_name' => 'ZOH',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@zohourclub.com',
                'phone' => '+20222600000',
                'manager_name' => 'علاء حسن',
                'arena' => 'صالة نادي الزهور بمدينة نصر',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'المعادي (Maadi SC)',
                'short_name' => 'MAA',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@maadiclub.org',
                'phone' => '+20223580000',
                'manager_name' => 'مصطفى حسين',
                'arena' => 'صالة نادي المعادي واليخت',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الترسانة (Tersana SC)',
                'short_name' => 'TER',
                'city' => 'الجيزة',
                'country' => 'مصر',
                'email' => 'handball@tersanaclub.com',
                'phone' => '+20233030000',
                'manager_name' => 'أشرف عبده',
                'arena' => 'صالة حسن الشاذلي بميت عقبة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'القناة (Al Qanah SC)',
                'short_name' => 'QAN',
                'city' => 'الإسماعيلية',
                'country' => 'مصر',
                'email' => 'handball@qanahclub.com',
                'phone' => '+20643320000',
                'manager_name' => 'مدحت عبد العال',
                'arena' => 'صالة هيئة قناة السويس بالإسماعيلية',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'أصحاب الجياد (Ashhab El Giyad)',
                'short_name' => 'GYD',
                'city' => 'الإسكندرية',
                'country' => 'مصر',
                'email' => 'handball@giyadclub.com',
                'phone' => '+2034280000',
                'manager_name' => 'إيهاب العاصي',
                'arena' => 'صالة نادي أصحاب الجياد بسموحة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
            [
                'name' => 'الشمس (Al Shams SC)',
                'short_name' => 'SHM',
                'city' => 'القاهرة',
                'country' => 'مصر',
                'email' => 'handball@shamsclub.com',
                'phone' => '+20221800000',
                'manager_name' => 'صابر حسين',
                'arena' => 'صالة نادي الشمس بمصر الجديدة',
                'status' => TeamStatus::ACCEPTED,
                'logo' => 'defaults/team-crest.png',
            ],
        ];

        foreach ($teams as $teamData) {
            Team::updateOrCreate(
                ['name' => $teamData['name']],
                $teamData
            );
        }
    }
}
